### ISSUE TITLE
Add version info

### ISSUE THREAD

**Issue by KingIzzymon** [webrcade/webrcade#101]
To help with development and bug reporting, it'd be great to include an "About" section within the settings gear to show the running version of webRcade (and maybe also docker version).

Also to add a docker label to indicate the webRcade version if we're always deploying the `:latest` tag.

**Comment by raz0red** [comment]
Albeit hidden, you can get to the version by doing navigating to the
following:

https://play.webrcade.com/VERSION.txt

Similar URL for Docker:

http://localhost/play/VERSION

**Comment by raz0red** [comment]
Albeit hidden, you can get to the version by doing navigating to the following:

https://play.webrcade.com/VERSION.txt

Similar URL for Docker:

http://localhost/play/VERSION

**Comment by KingIzzymon** [comment]
Good to know, thanks.

I'll close this issue for now since there are so many open.
