### ISSUE TITLE
Support more emulators

### ISSUE THREAD

**Issue by Protektor-Desura** [webrcade/webrcade#129]
There are some emulators missing that you could support that have JS/Web emulator versions. If you check out the Linuxserver JS version they have a few extra emulators that you don't have:
https://github.com/linuxserver/emulatorjs
https://github.com/linuxserver/docker-emulatorjs
https://github.com/thelamer/retrostash

Like:
3DO
Atari Jaguar
Doom
Magnavox Odyssey 2
Mattel Intellivision
Microsoft MSX/MSX2
Nintendo DS
Quake
Vectrex
& OTHERS

Another option you could add is to support DOSBox which has a web version & possibly ScummVM which also has a web version.
https://github.com/dreamlayers/em-dosbox
https://github.com/gr33k/emscripten-scummvm

Quake 1
https://github.com/Darksecond/jsQuake

Quake 2
https://github.com/p3rl/quake2js

Quake 3
https://github.com/inolen/quakejs

Half-Life: Uplink, Half-Life: Deathmatch, Half-Life: Day One
https://github.com/iCrazyBlaze/Xash3D-Emscripten

Homeworld
https://github.com/GardensOfKadesh/Homeworld

**Comment by Protektor-Desura** [comment]
Here is a better & official link for the emscripten version of ScummVM
https://github.com/scummvm/scummvm/tree/master/dists/emscripten

**Comment by raz0red** [comment]
Closing this issue as it is not really deterministic when it would be completed.

Instead, could you please open an issue for each system you would like to have added. That way, we can better track progress toward each individual one.

Also the following are already available:

Quake
Doom (limited support, but a separate defect is already listed to add full support #21)

And issues exist for the following:

Nintendo DS #55 
ScummVM #32
