### ISSUE TITLE
Feature Request: add ability to pass prebuilt feed url when launching webrcade

### ISSUE THREAD

**Issue by h0gg1e** [webrcade/webrcade#15]
AMAZING PROJECT!!!!

Not sure if possible but it would be be cool to be able to pass in a feed url while launching webrcade. that way a url could be bookmarked and launched directly into a saved feed.

also mame or fba would be amazing on a iOS device

**Comment by raz0red** [comment]
Actually, it already supports that:

`https://play.webrcade.com?feed=<feed url>`

Let me know if you have any issues,
Thanks!
