### ISSUE TITLE
Sound delay on all platforms

### ISSUE THREAD

**Issue by mardem1976** [webrcade/webrcade#16]
I’m experiencing a very noticeable lag for sound with all emulators. I’m using the site via iOS on an iPhone 13 pro max. Controls are spot on with my mfi controller, but sounds emit almost a half second after they should.

I’ve played with other emulators in the browser before and don’t see this issue.

**Comment by mardem1976** [comment]
This seemed to have resolved itself. Audio seems to be working fine now.

**Comment by raz0red** [comment]
That is great news! By any chance was your battery low?

**Comment by mardem1976** [comment]
It may have been at one point, but I don't think it was all the time I was using it. I'll keep an eye on it and open this up if I see it pop up again.
