### ISSUE TITLE
Dockerfile build fails due to missing roms-scummvm.json file

### ISSUE THREAD

**Issue by Aman7123** [webrcade/webrcade#161]
1. **Summary:**
   - The Docker build process for the `webrcade` repository fails due to a missing file, `roms-scummvm.json`, which is required by `createdats.js`. This file is not fetched by the `dist.sh` script from the `webrcade-utils` repository.

2. **Details:**
   - During the Docker build, the `dist.sh` script executes `createdats.js`. However, `createdats.js` depends on `roms-scummvm.json`, which is not present in the Docker build context. 
   - The `roms-scummvm.json` file exists in the `webrcade-utils` repository, but `dist.sh` does not include a command to fetch it.

3. **Steps to Reproduce:**
   - Clone the `webrcade` repository.
   - Run the Docker build command.

4. **Expected Behavior:**
   - The Docker build should complete successfully without errors.

5. **Actual Behavior:**
   - The build process fails because `createdats.js` cannot find the `roms-scummvm.json` file.

6. **Proposed Solution:**
   - To resolve this issue, I suggest adding the following command to the `dist.sh` script before the `node "$UTILS/createdats.js"` line, anywhere within [this section of the dist.sh code](https://github.com/webrcade/webrcade/blob/49f3a624e72c76d3c81eed0e738a400acb224f4e/dist.sh#L45-L66):
     ```bash
     wget -O - https://webrcade.github.io/webrcade-utils/roms-scummvm.json > roms-scummvm.json ||
         { fail 'Unable to retrieve roms json.'; }
     ```
   - This command will fetch `roms-scummvm.json` from the `webrcade-utils` repository and allow the Docker build to complete successfully.

**Comment by raz0red** [comment]
Thanks for reporting, this should be fixed now.

Please let me know if it works for you and I will close this issue.

**Comment by Aman7123** [comment]
Fantastic help @raz0red, the docker build is working now. Thank you!

**Comment by raz0red** [comment]
No problem, thanks a lot for reporting it.
