### ISSUE TITLE
SNES Super Multitap

### ISSUE THREAD

**Issue by microSCOPED** [webrcade/webrcade#18]
Is there a way to build the SNES application backend with support for the Super Multitap? There may only be a handful of games that support it but they are awesome.

**Comment by raz0red** [comment]
Definitely possible, I will look into it. Thanks for reporting!

**Comment by raz0red** [comment]
There is a preliminary version of the app on the following test server:

https://play-staging.webrcade.com
https://editor-staging.webrcade.com

In the editor for snes, there is a new option to enable multi tap on port 2. If you could give it a shot, that would be great. I tested with 3 controllers, but it should work with up to 5.

I was hoping to push this change along with a couple others to the main page late tonight.

**Comment by microSCOPED** [comment]
I just tested it [only had 2 controllers and a keyboard] with Bomberman 2 and it worked fine.

**Comment by raz0red** [comment]
Released in 0.0.1
