### ISSUE TITLE
Issue, GBA saves not keeping between sessions.

### ISSUE THREAD

**Issue by msmith067** [webrcade/webrcade#19]
I’m running Metroid fusion for GBA and it’s working great.  Except for saves.  They seemed to be working fine at first, but now when I save, the save point isn’t updated.  The next time I load the save I’m back to the same point before my last save.  I lose all my progress.   Any thoughts?

**Comment by basvroegop** [comment]
Did you open the Webrcade menu after saving by tapping your screen?

**Comment by msmith067** [comment]
I don’t think so.  Should I?  Easy to test if I know what I should do

**Comment by msmith067** [comment]
Going back to the menu seems to have fixed it.  I’ll test some more.
does the save file only write out of memory to the file when you exit to the menu?

**Comment by raz0red** [comment]
Closing as it appears to be working as designed.

When cloud saves are enabled, hopefully this makes a bit more sense. There will also be additional status messages added to make it clear what is happening.
