### ISSUE TITLE
Create Items From URLs doesn't accept new lines as stated

### ISSUE THREAD

**Issue by jmt-gh** [webrcade/webrcade#23]
**Description**
The Create Items from URLs wizard states that you should provide URLs, 1 on each line, but it doesn't actually accept new lines. I've attempted to both copy in URLs that are already new line separated, as well as manually insert them in the modal. Instead, it appears to accept / require space separated URLs.

This screenshot shows it properly parsing space separated URLs (I used garbage text here, but the same behavior occurred with real URLs), but I wasn't able to add in new lines.

![image](https://user-images.githubusercontent.com/13617455/150651837-1b9cbf32-8914-4d7c-811a-5369b9087632.png)

**Comment by raz0red** [comment]
I am unable to reproduce this. What browser and platform are you using? Thanks!

**Comment by raz0red** [comment]
Unable to reproduce, please re-open if you can reproduce. Thanks!
