### ISSUE TITLE
local links

### ISSUE THREAD

**Issue by jdeath** [webrcade/webrcade#24]
This looks good. Can you make the links relative. I am trying to run via a proxy, and not having all links relative is messing thigs up. Seems much faster than emulatorjs

**Comment by raz0red** [comment]
Can you provide an example of a relative link that isn't working for you? Thanks

**Comment by raz0red** [comment]
Were you able to resolve this? Just curious.

**Comment by jdeath** [comment]
No, not resolved, but I think I have a unique use case not worth your effort. I am loading the docker via homeassistant, which basically reverse proxy's the server. Often if links are not relative, things do not work. Here is a screenshot. Some images do not load (notice title banner or the play icon), nor can I play a game (think the API is calling absolute links too). If I got to the IP:port directly instead of the proxy, everything works fine and games play fine.
![image](https://user-images.githubusercontent.com/17914369/152894486-a079b733-3f01-499b-94ab-99ea7012b4e6.png)

**Comment by raz0red** [comment]
Hmmm... not sure why that is. 

There are no absolute paths anywhere, it is all relative. In fact, in development, I use completely different paths, etc. So, not sure why that is occurring.
