### ISSUE TITLE
Unable to connect to docker build

### ISSUE THREAD

**Issue by killkong1211** [webrcade/webrcade#26]
Hey there,

So just tried to run the docker build, and it seems to have built successfully, but I can't access the service.
I composed it with port 87 exposed, but when I navigate to server.ip:87 it just throws back site cannot be reached.

I have several other apps running from this server no worries and can all be accessed this way, so hoping for a little help to get this up and running :)

**Comment by killkong1211** [comment]
`  GNU nano 3.2                                                                                                                                                                docker-compose.yaml                                                                                                                                                                          
version: "3"
services:
  webrcade:
    image: webrcade/webrcade
    container_name: webrcade
    restart: always
    ports:
      - 87:8080
`

My docker compose for ref

**Comment by killkong1211** [comment]
I realized that last night after posting haha.
Changed it to 87:80 and rebuilt the container to be safe.
Still didn't work though unfortunately.

**Comment by raz0red** [comment]
Not really sure. You could ask in the Discord, I know a lot of people have been using it. You can also pull it directly from docker hub vs. building it, but I doubt that will make a difference.

**Comment by killkong1211** [comment]
Change from port 87 to 8080 as suggested worked a treat.
