### ISSUE TITLE
Crackling/choppy sound on Xbox Series X

### ISSUE THREAD

**Issue by SuperMantis** [webrcade/webrcade#33]
Hi,

Followed the user guide on setting everything up on the Xbox Series X and most seem to be working fine. However, for some reason the sound is crackling/choppy for all the games I've tested so far for NES, SNES and SEGA.

Have tried changing the sound output settings on Xbox Series X, but nothing seems to fix the issue. 

Is this a known issue with a fix perhaps?

**Comment by raz0red** [comment]
No, you should not be experiencing choppy audio with Xbox Series X|S systems.

Choppy audio indicates that the games are not running at full speed. To confirm this, you can turn on debug:
https://play.webrcade.com?debug=1

Some things to try:
1.) Make sure borders are disabled for apps (video settings for xbox)
2.) Make sure hardware acceleration is enabled (browser settings)
3.) After confirming/setting those, exit out of Edge, open the side menu (xbox button), hover over the Edge application, press the menu button and select "Quit".
4.) Then, launch Edge again and confirm the borders disabled and hardware acceleration options have persisted

If that doesn't resolve the issue, please let me know,
Thanks!

**Comment by SuperMantis** [comment]
Hi raz0red,

Thanks for the debug string and the other tips which I’ve confirmed to be correctly set up.

I can now see the FPS and it turns out the games do not run at full speed for the first 25 seconds after launch. However, after those 25 seconds, the games seem to run at full speed with no audio issues.

Not sure if this is perhaps an isolated issue, but I’m running my game feed from DropBox if that helps.

Would be awesome to get this issue fixed, but not the end of the world to just have to wait 25 seconds, cheers! :)

**Comment by raz0red** [comment]
Yeah, that is VSYNC detection that was added. For some reason certain Xbox systems seem to perform poorly when VSYNC is enabled. I am thinking it may have to do with the display resolution and/or refresh rate.

What are you current video settings for your Xbox?

Thanks!

**Comment by raz0red** [comment]
Were you able to validate whether this was resolved w/ VSYNC detection? 
Adding an enable/disable flag makes sense.

**Comment by raz0red** [comment]
You can now disable VSYNC via settings (currently on staging). However, will be part of the 0.0.5 release.
