### ISSUE TITLE
[Feature Request] Category-wide Property setting for "stretch to screen"

### ISSUE THREAD

**Issue by Emreler1** [webrcade/webrcade#36]
It would be great to have the option to stretch the smaller sized gameplay area to the whole screen, especially when playing from a smaller device like a phone.

**Comment by sysconf16** [comment]
This would also be useful for devices like iPads which have 4:3 aspect ratios, but still leave black bars around the edges as the render windows defined by the emulators do not span the full screen space.

**Comment by raz0red** [comment]
Some possible option:

- Stretch to fit (horizonal)
- 16:9
- ...

On some devices stretch to fit will be way too wide, so maybe providing something like 16:9 would be desirable.

Also, I am not sure exactly what to do w/ vertically oriented games. Stretching those to fit will look really bad. Maybe I just ignore this setting for vertical games? Any thoughts?

**Comment by Emreler1** [comment]
Then maybe a tickbox for "Apply this even to vertical games" could be handy?

**Comment by raz0red** [comment]
Yeah, that makes sense. I will put something together once I get 0.0.5 released publicly. This should be a quick one to get in.

**Comment by raz0red** [comment]
This option is available in 0.1.1
