### ISSUE TITLE
Higher Resolution Support

### ISSUE THREAD

**Issue by sysconf16** [webrcade/webrcade#43]
When opening the webЯcade UI on a device with a resolution higher than 1920 x 1080, a black border appears.
![image](https://user-images.githubusercontent.com/101810247/166268405-e63075d2-f0f2-4315-9b73-d40f6335a381.png)
Automatic scaling with higher resolutions would help to overcome this.

**Comment by raz0red** [comment]
Yeah, that is something I will address in the future.

In the mean time, you can zoom in and it should allow for scaling to larger screens (modern browsers will also persist this zoom level per site).

**Comment by sysconf16** [comment]
Yes, that's the workaround I'm currently using for myself.

It's just that it can become a little tedious for others who are less technically competent, family members for example, where it would be ideal for things to work out of the box.

**Comment by raz0red** [comment]
There is pull request (https://github.com/webrcade/webrcade/issues/50) by @nydemeth.

I will be working to integrate this into the next release (post 0.0.4).

Thanks a lot!

**Comment by raz0red** [comment]
This is currently implemented on staging:
https://play-staging.webrcade.com
https://editor-staging.webrcade.com
