### ISSUE TITLE
PlayStation Emulation

### ISSUE THREAD

**Issue by sysconf16** [webrcade/webrcade#46]
Several browser-based PlayStation emulators already exist online. Making this system available on webЯcade would help bring 3D games to the platform.

**Comment by raz0red** [comment]
Agreed. It is in the queue after the next couple of releases.

**Comment by raz0red** [comment]
PlayStation will be the next release.  
Sorry about the delay, but I wanted to get it right.

**Comment by raz0red** [comment]
Available in 0.0.6
