### ISSUE TITLE
Idea - feed in the frontend link

### ISSUE THREAD

**Issue by Crover81** [webrcade/webrcade#49]
I think it would be nice to be able to optionally upload your own feeds by placing a link directly on the front end link

example: localhost:8080/feed=https://pastebin.com/2yfYHZKi

I don't know if this is possible, it's just an idea
In any case, I really appreciate your project!

**Comment by raz0red** [comment]
Actually, that already works, but the format is as follows:

`https://play.webrcade.com?feed=<my_feed_url>`

Thanks!
