### ISSUE TITLE
Adding NEO•GEO roms / Only identifies 3 games...

### ISSUE THREAD

**Issue by Koujibear76** [webrcade/webrcade#56]
So NEO•GEO rom files look like most MAME rom files, with extremely abbreviated file names. I don't think I have ever come across a NEO•GEO rom set with "correct" file names. This has never been an issue for me; Not with my retro handhelds or RetroArch or LaunchBox, etc. WebRcade seems to have a problem matching those rom file names to the corresponding games. Am I gonna have to rename over a hundred files to make this work??

**Comment by raz0red** [comment]
Hi-

Webrcade's Neo Geo (and other arcade) support is based on FBNeo, not MAME. 

https://docs.webrcade.com/apps/emulators/neogeo/
and
https://docs.webrcade.com/apps/emulators/arcade/

If you have a FBNeo compatible ROM set (for a recent version), you won't have to rename anything. 

I am sorry to hear that you are having issues. If you would like some additional help, please message me on the webRcade Discord and I will gladly help you out.

Thanks.
