### ISSUE TITLE
Docker - Add ARM Support

### ISSUE THREAD

**Issue by zDEFz** [webrcade/webrcade#58]
Would be great so I could run it on my m1 mac. And my other m1 mac running Linux. And my Raspberry Pi running ARM

**Comment by raz0red** [comment]
Hi-

Webrcade uses WebAssembly and is not bound to a specific processor architecture. Can you please provide a bit more detail?

Thanks!

**Comment by zDEFz** [comment]
`def@mini:~ -$ docker run -d --name=webrcade -e PUID=1000 -e PGID=1000 -p 3002:80 -e TZ=Europe/London -e / -v /home/def/emulatorjs/data:/data --restart unless-stopped webrcade/webrcade

zsh: correct '/home/def/emulatorjs/data:/data' to '/home/def/emulatorjs/data/data' [nyae]? n
Unable to find image 'webrcade/webrcade:latest' locally
latest: Pulling from webrcade/webrcade
42c077c10790: Pull complete
8934009a9160: Pull complete
5357ac116991: Pull complete
54ae63894b5a: Pull complete
772088206f85: Pull complete
3b81c5474649: Pull complete
c62a528527ae: Pull complete
63666c622ffa: Pull complete
0de5e53aad5f: Pull complete
8e05551834b5: Pull complete
cf8fbd2cecc4: Pull complete
6c8265911726: Pull complete
7852d9eb2ff4: Pull complete
d7e9d73f59dc: Pull complete
51a970e742a9: Pull complete
23b749b66481: Pull complete
69ed2ee665a6: Pull complete
f7c0218441b4: Pull complete
1a2a04bf77ae: Pull complete
2cc6623cc329: Pull complete
088bc39dee2d: Pull complete
09dfc4188799: Pull complete
Digest: sha256:4a74f9f0e5d555cfc6b15d9cf7637700f3aebf29752e2a0d25abd5b60303655b
Status: Downloaded newer image for webrcade/webrcade:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
45d28b9630a93862d6e9eb7dd6f4ad65496c4fbdc91415e02057d7879a4b8914
def@mini:~ -$
`

**Comment by zDEFz** [comment]
https://hub.docker.com/r/webrcade/webrcade/tags I dont see a ARM build here

**Comment by raz0red** [comment]
Gotcha, the Docker part was what I was missing (I thought you were just using the public site). 

Sounds good, thanks!

**Comment by raz0red** [comment]
So, it looks like Docker Hub doesn't support an ARM-based automated build (not sure why).

Probably the best option would be to have the Docker images built in Git and then published to Docker. This is something I will look at when I get a spare minute.

In the mean time, have you tried building the image on ARM? (checked out the repo and performed a build).

Thanks.

**Comment by zDEFz** [comment]
Successfully built 548144ca293b
Successfully tagged webrcade:latest

**Comment by raz0red** [comment]
Nice! 

Ok, well, I need to figure out a way to do the builds as part of GitHub vs. relying on Docker Hub's automated builds.

Also, you can export that image and then import it on other systems (you don't have to perform the build again on each system).

Thanks again for testing all that out!

**Comment by marcb199** [comment]
Hi, I'm trying to build an ARM image for my M1 Mac Mini, but it's throwing an error while building. I have never built an image for docker before and I'm relatively inexperienced with docker so I might be missing something here: 

#0 143.1 Installed to /webrcade/node_modules/node-sass/vendor/linux-arm64-72/binding.node
#0 143.7 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
#0 143.7 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#0 143.7 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
#0 143.7 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#0 143.7 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
#0 143.7 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#0 143.7 
#0 143.7 + archiver@5.3.1
#0 143.7 added 2054 packages from 780 contributors and audited 2057 packages in 66.767s
#0 143.7 found 63 vulnerabilities (2 low, 14 moderate, 27 high, 20 critical)
#0 143.7   run `npm audit fix` to fix them, or `npm audit` for details
#0 143.7 --2022-08-06 09:06:19--  https://webrcade.github.io/webrcade-utils/createdats.js
#0 143.7 Resolving webrcade.github.io (webrcade.github.io)... 185.199.110.153, 185.199.109.153, 185.199.111.153, ...
#0 143.7 Connecting to webrcade.github.io (webrcade.github.io)|185.199.110.153|:443... connected.
#0 143.8 HTTP request sent, awaiting response... 200 OK
#0 143.9 Length: 15989 (16K) [application/javascript]
#0 143.9 Saving to: 'STDOUT'
#0 143.9 
#0 143.9      0K .......... .....                                      100% 8.69M=0.002s
#0 143.9 
#0 143.9 2022-08-06 09:06:19 (8.69 MB/s) - written to stdout [15989/15989]
#0 143.9 
#0 143.9 internal/modules/cjs/loader.js:800
#0 143.9     throw err;
#0 143.9     ^
#0 143.9 
#0 143.9 Error: Cannot find module './roms-fbneo.json'
#0 143.9 Require stack:
#0 143.9 - /webrcade/public/createdats.js
#0 143.9     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
#0 143.9     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
#0 143.9     at Module.require (internal/modules/cjs/loader.js:852:19)
#0 143.9     at require (internal/modules/cjs/helpers.js:74:18)
#0 143.9     at Object.<anonymous> (/webrcade/public/createdats.js:4:15)
#0 143.9     at Module._compile (internal/modules/cjs/loader.js:959:30)
#0 143.9     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
#0 143.9     at Module.load (internal/modules/cjs/loader.js:815:32)
#0 143.9     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
#0 143.9     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
#0 143.9   code: 'MODULE_NOT_FOUND',
#0 143.9   requireStack: [ '/webrcade/public/createdats.js' ]
#0 143.9 }
#0 143.9 Unable to execute create dats.
#0 143.9 Exiting.
------
Dockerfile:34
--------------------
  32 |     COPY docker/config.json /webrcade-app-common/src/conf/
  33 |     
  34 | >>> RUN cd /webrcade && ./dist.sh 
  35 |     RUN wget -O - https://webrcade.github.io/webrcade-utils/cors.php > /webrcade/dist/out/cors.php
  36 |     RUN cd /webrcade && ./dist-package.sh
--------------------
error: failed to solve: process "/bin/sh -c cd /webrcade && ./dist.sh" did not complete successfully: exit code: 1


Any help would be appreciated. Thanks!

**Comment by zDEFz** [comment]
are you on macos or on asahilinux?

**Comment by marcb199** [comment]
MacOS. Tried building it with a Ubuntu VM but the same error occurred.

**Comment by zDEFz** [comment]
Can u post the entire log chain of commands and upload it to https://pastebot.rmdir.de/ ?

**Comment by marcb199** [comment]
Sorry, posted the output using the link you provided. Thanks for your help!

**Comment by raz0red** [comment]
It seems like it is missing steps. Did you clone or download the latest code on main?

https://github.com/webrcade/webrcade/archive/refs/heads/master.zip

**Comment by marcb199** [comment]
Thanks for your reply. I thought I downloaded everything i needed, but apparently I didn't. Used your link and the build was successful. Thank you!
Now I just need to figure out where it stored the image. Do you have an idea? Sorry for the noob questions.

**Comment by raz0red** [comment]
If you do the following, it will be in the local registry:

`docker build -t webrcade .`

Then you can run it:

`docker run -d --name=webrcade webrcade:latest`

You can also add extra options like (volume mounting, ports, etc.):

`docker run -d --name=webrcade  -v /home/webrcade/data:/data --restart unless-stopped webrcade:latest`

You can also export the image and subsequently load it on other systems.

**Comment by marcb199** [comment]
This worked perfectly, thank you!
And great application by the way!

**Comment by raz0red** [comment]
Great to hear! And, thanks, really appreciate it!

**Comment by rcarmo** [comment]
Hi! Just wanted to give you a little nudge here on the multiarch front - have a look at https://github.com/rcarmo/github-actions-multiarch-docker for a sample flow. There have been some changes to GitHub Actions, but this approach can be tested locally on a Linux machine as well.

**Comment by raz0red** [comment]
Ah, nice! Thanks @rcarmo.

This looks straight-forward and is exactly what I was looking for. At first glance, I didn't see version tagging supported, do you happen to know if this is only LATEST? I am guessing I can modify it to apply to most tags as well (versus just pushes to main, etc.).

**Comment by raz0red** [comment]
This is now available on Docker Hub (part of release 0.1.1).
