### ISSUE TITLE
How to access the editor when running a docker container

### ISSUE THREAD

**Issue by muditjuneja** [webrcade/webrcade#60]
Everything seems to work except, that I cannot open up the editor. Is it part of the image? I guess it is as it was being pulled from the bash scripts.
I tied accessing it here : http://localhost:8081/editor
But it gives 404. Can you help @raz0red ?

**Comment by muditjuneja** [comment]
Hi @raz0red, Actually it works here: http://localhost:8081/play/app/editor/
But I have a follow-up issue, I can not see already loaded categories and games. See the image. 
<img width="1722" alt="Screenshot 2022-08-19 at 2 04 39 AM" src="https://user-images.githubusercontent.com/15162221/185489719-9f5dd04c-df0c-4f9f-993d-ad0afb8adc08.png">

What could be the issue with this?

**Comment by muditjuneja** [comment]
I think, locally it doesn't load default-feed.json. Have a look at the Network dump from my local run and from https://play.webrcade.com/app/editor/
[Network calls.zip](https://github.com/webrcade/webrcade/files/9377491/Network.calls.zip)

**Comment by raz0red** [comment]
Correct, the Docker based image does not load the default feed. But, you can import it.

**Comment by muditjuneja** [comment]
@raz0red  yeah, I was able to add a new feed. So you are saying that there is no way to update the default loaded feed. Will I have to deploy again after changing the default-feed.json? I just want the games I play and the rest is all clutter to me.

**Comment by raz0red** [comment]
You can host your feed locally and just point to that URL in the player/editor.
