### ISSUE TITLE
dosnt see any controls

### ISSUE THREAD

**Issue by gotshadowbantempaccount** [webrcade/webrcade#72]
maybe usability issue ?

What do to play when touch show view controls do i have to connect my switch pad ?

![image](https://user-images.githubusercontent.com/88304290/192130290-fa44eb98-9132-424c-ac1e-d3532a90b26d.png)

**Comment by raz0red** [comment]
Currently, requires a physical controller or keyboard. 

Virtual controllers will be added in a future release.
