### ISSUE TITLE
Cloud storage dont work at all

### ISSUE THREAD

**Issue by TheDonAlex** [webrcade/webrcade#74]
Ive linked webRcade to dropbox on my Firefox Browser. After a short playtime ive exited the game, and instant restarted it. It started from the beginning. I have also checked on my iPhone Safari browser, same result. Is there something I can do?

**Comment by raz0red** [comment]
Hi-
Sorry to hear about that. The current save support is in-game saves only. It will only persist to the cloud if the game itself has create a save. Then, when you show the menu, or exit it will sync to the cloud. 

A prompt will be displayed when it is saving to the cloud.

Full save state support will be coming in an upcoming release.

Hopefully that helps, please let me know if something else is happening,
Thanks,
Chris

**Comment by TheDonAlex** [comment]
Hi Chris,
first of all there is no sorry. Its a free service and i'm thankfull for it!

Your answer helps a lot. I thought it will save the state i'm live in. Like an offline emulator. But now I get it. If the game creates a savegame it will be synced. 

I tested it and it worked perfectly. Great!

Looking forward for the full save state support.

Thanks once again for the fast answer to make it clear for me.
