### ISSUE TITLE
N64 error 'undefined is not an object' on 2020 iPad Air 14.4

### ISSUE THREAD

**Issue by boazdejong** [webrcade/webrcade#92]
I'm getting the following message when trying to run a N64 game in safari on my 2020 iPad Air (iPadOS 14.4)

`undefined is not an object (evaluating 'GLctx[createFunction])`

It runs fine when running in safari on my Macbook.

![IMG_C3AFE8A463D2-1](https://user-images.githubusercontent.com/4102106/199488019-00c1622b-0873-4b39-8843-8d11ea24ea6d.jpeg)

**Comment by raz0red** [comment]
Hmmm, that is odd. 14.4 is pretty old, so I am unable to test on it. 

I wonder if there is a Safari advanced setting that is disabled related to webGL.

**Comment by raz0red** [comment]
I know it is probably not something you want to do. But, I am thinking if you upgraded that error might go away. It could have to do with the fact that it is looking for a newer version of the context.

**Comment by boazdejong** [comment]
It works! I had to turn on 'WebGL 2.0' in the Experimantal Features in the Safari Advanced settings. Thank you for your help! Unfortunately it's not really playable on my iPad Air due to performance issues. I wonder if upgrading will help with that.

**Comment by raz0red** [comment]
Your iPad Air should be able to play quite a number of games at full speed.  Is it the 4th generation? 
I am unsure if upgrading would help improve performance (it might). 
One thing to check, make sure `"GPU Process: WebGL"` is **disabled**. If not, it will have very poor performance.

See this page for more details: https://docs.webrcade.com/apps/emulators/n64/

**Comment by boazdejong** [comment]
Yes it is a 4th generation iPad Air. I will update to 16.1 and see if it helps. Thank you for your help!

**Comment by raz0red** [comment]
Just out of curiosity, is` "GPU Process: WebGL"` enabled or disabled on your iPad?
Thanks!

**Comment by boazdejong** [comment]
That's not on the list of Experimental Features on iPadOS 14.4

There is `"WebGPU"` which I tried turning on. But that didn't make a difference.

**Comment by boazdejong** [comment]
Wow upgrading to 16.1 and turning off `"GPU Process: WebGL"` gave a huge performance boost! It runs great now! 🎉

**Comment by raz0red** [comment]
It is already available. :-)

**Comment by boazdejong** [comment]
That's awesome, I'm going to try that right away! I was just playing Super Mario 64 on my TV through AirPlay with a PS4 controller and it works amazing!

**Comment by raz0red** [comment]
Very cool! Great to hear. If you have any issues, just let me know.

Thanks again!
